import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.scss";
import ThemeRegistry from "@/theme/theme-registry";
import { Box } from "@mui/joy";

const openSans = Open_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" data-color-scheme="dark" >
      <body className={`${openSans.variable}`}>
        <ThemeRegistry options={{ key: 'joy' }}>
          <Box bgcolor={'background.body'}>
            {children}
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}
